trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool: Ubuntu
    variables: 
    - group: TeraformEnvVars
    steps:
    - script: |
        set -e
        echo "DB_USER: \"$TF_VAR_db_user\"" >> src/db_conf.yaml
        echo "DB_PASS: \"$TF_VAR_db_pass\"" >> src/db_conf.yaml
        sudo docker build . -t sunshine2050/demo-app:$(tag)
        sudo docker push sunshine2050/demo-app:$(tag)
      name: 'RunDocker'
      displayName: 'Run Docker'
      env:
        TF_VAR_db_user: $(DB_USER)
        TF_VAR_db_pass: $(DB_PASS)
- stage: Plan
  displayName: 'Terraforming on Azure...'
  dependsOn: Build
  jobs:
  - job: Plan
    displayName: 'Planning Container Instance'
    pool: Ubuntu
    variables: 
    - group: TeraformEnvVars
    steps:
    - script: |
        set -e
        cd terraform/
        terraform init -input=false
        terraform plan

        terraform apply -input=false -auto-approve
      name: 'RunTerraform'
      displayName: 'Run Terraform'
      env:
        ARM_CLIENT_ID: $(ARM_CLIENT_ID)
        ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)
        ARM_TENANT_ID: $(ARM_TENANT_ID)
        ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)
        TF_VAR_image_build: $(tag)
        TF_VAR_db_user: $(DB_USER)
        TF_VAR_db_pass: $(DB_PASS)

- stage: ManualProvisionApproval
  displayName: 'Approving ...'
  dependsOn: Plan
  jobs:
  - job: ApprovalStage
    displayName: 'Approving terradform provisioning'
    pool: Ubuntu
    steps:
      - task: ManualIntervention@8
        inputs:
          instructions: 'Do you approve ?'
- stage: Provision
  displayName: 'Terraforming on Azure...'
  dependsOn: ManualProvisionApproval
  jobs:
  - job: Provision
    displayName: 'Provisioning Container Instance'
    pool: Ubuntu
    variables: 
    - group: TeraformEnvVars
    steps:
    - script: |
        set -e
        cd terraform/
        terraform apply -input=false -auto-approve
      name: 'RunTerraform'
      displayName: 'Run Terraform'
      env:
        ARM_CLIENT_ID: $(ARM_CLIENT_ID)
        ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)
        ARM_TENANT_ID: $(ARM_TENANT_ID)
        ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)
        TF_VAR_image_build: $(tag)
        TF_VAR_db_user: $(DB_USER)
        TF_VAR_db_pass: $(DB_PASS)