trigger:
- master

resources:
- repo: self

stages:
- stage: Install_run_Ansible
  displayName: Install and run Ansible
  pool:
    vmImage: 'ubuntu-focal'
  jobs:
  - job: Install_run_Ansible
    displayName: Install and Run Ansible
    steps:
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          sudo apt-add-repository ppa:ansible/ansible
          sudo apt-get update
          sudo apt install ansible
          ansible-playbook playbook.yaml